spring:
  application:
    name: sparkle-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/db_sparkle?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  sql:
    init:
      schema-locations: classpath:hero/initSchema.sql
      #data-locations: classpath:hero/initData.sql
      mode: always

server:
  port: 8888
  servlet:
    #可以定义成如/api
    context-path: /

sparkle:
  publish-dir: D:\Code\sparkle\sparkle-server\backTmp

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/**/*.xml
    - classpath:/hero/mapper/**/*.xml