spring:
  application:
    name: hero-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD:12345}
    url: jdbc:mysql://127.0.0.1:3306/db_hero?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
  sql:
    init:
      schema-locations: classpath:initSchema.sql
      #data-locations: classpath:initData.sql
      mode: always

server:
  port: 8889
  servlet:
    context-path: /hero

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml